# Generated by Django 3.2 on 2021-05-07 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_fact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Fact',
        ),
    ]
