# Generated by Django 3.2 on 2021-05-07 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_delete_fact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('data', models.CharField(max_length=300)),
                ('result', models.CharField(blank=True, max_length=300)),
            ],
        ),
    ]
