# Generated by Django 3.2 on 2021-05-07 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_qualification'),
    ]

    operations = [
        migrations.CreateModel(
            name='Myplan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('forwhat', models.CharField(max_length=300)),
                ('transfer', models.CharField(max_length=300)),
                ('style', models.CharField(max_length=300)),
                ('service', models.CharField(max_length=300)),
                ('price', models.CharField(max_length=300)),
            ],
        ),
    ]
