# Generated by Django 3.2 on 2021-05-07 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_myplan'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Myplan',
        ),
    ]
